service: alexa-johnny

frameworkVersion: ">=1.4.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  profile: nordstrom-federated
  role: arn:aws:iam::997544667679:role/DeployBot-Lambda-role
  timeout: 100

functions:
  alexaHandler:
    handler: src/alexa/index.handler
    events:
      - alexaSkill